apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity-hello-go
  template:
    metadata:
      labels:
        app: velocity-hello-go
    spec:
      containers:
        - name: velocity-hello-go
          image: arielvelocity/velocity-hello-go:latest
          ports:
            - containerPort: 8080
